# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PlateFinder(object):
    def setupUi(self, PlateFinder):
        PlateFinder.setObjectName("PlateFinder")
        PlateFinder.setWindowModality(QtCore.Qt.NonModal)
        PlateFinder.setEnabled(True)
        PlateFinder.resize(947, 678)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PlateFinder.sizePolicy().hasHeightForWidth())
        PlateFinder.setSizePolicy(sizePolicy)
        PlateFinder.setSizeGripEnabled(False)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(PlateFinder)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(PlateFinder)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.inImg = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inImg.sizePolicy().hasHeightForWidth())
        self.inImg.setSizePolicy(sizePolicy)
        self.inImg.setMinimumSize(QtCore.QSize(200, 50))
        self.inImg.setScaledContents(True)
        self.inImg.setAlignment(QtCore.Qt.AlignCenter)
        self.inImg.setObjectName("inImg")
        self.horizontalLayout_3.addWidget(self.inImg)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.groupBox = QtWidgets.QGroupBox(PlateFinder)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.plateList = QtWidgets.QListWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plateList.sizePolicy().hasHeightForWidth())
        self.plateList.setSizePolicy(sizePolicy)
        self.plateList.setMinimumSize(QtCore.QSize(100, 0))
        self.plateList.setObjectName("plateList")
        item = QtWidgets.QListWidgetItem()
        self.plateList.addItem(item)
        self.verticalLayout.addWidget(self.plateList)
        self.horizontalLayout.addWidget(self.groupBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_4 = QtWidgets.QGroupBox(PlateFinder)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.plateImg = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plateImg.sizePolicy().hasHeightForWidth())
        self.plateImg.setSizePolicy(sizePolicy)
        self.plateImg.setMinimumSize(QtCore.QSize(70, 30))
        self.plateImg.setScaledContents(True)
        self.plateImg.setAlignment(QtCore.Qt.AlignCenter)
        self.plateImg.setObjectName("plateImg")
        self.verticalLayout_4.addWidget(self.plateImg)
        self.horizontalLayout_2.addWidget(self.groupBox_4)
        self.groupBox_2 = QtWidgets.QGroupBox(PlateFinder)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.bWeb = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bWeb.sizePolicy().hasHeightForWidth())
        self.bWeb.setSizePolicy(sizePolicy)
        self.bWeb.setObjectName("bWeb")
        self.verticalLayout_3.addWidget(self.bWeb)
        self.bClr = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bClr.sizePolicy().hasHeightForWidth())
        self.bClr.setSizePolicy(sizePolicy)
        self.bClr.setObjectName("bClr")
        self.verticalLayout_3.addWidget(self.bClr)
        self.bLoad = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bLoad.sizePolicy().hasHeightForWidth())
        self.bLoad.setSizePolicy(sizePolicy)
        self.bLoad.setObjectName("bLoad")
        self.verticalLayout_3.addWidget(self.bLoad)
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.retranslateUi(PlateFinder)
        QtCore.QMetaObject.connectSlotsByName(PlateFinder)

    def retranslateUi(self, PlateFinder):
        _translate = QtCore.QCoreApplication.translate
        PlateFinder.setWindowTitle(_translate("PlateFinder", "Plate Finder"))
        self.groupBox_3.setTitle(_translate("PlateFinder", "Input image"))
        self.inImg.setText(_translate("PlateFinder", "No image loaded"))
        self.groupBox.setTitle(_translate("PlateFinder", "Detected plates"))
        __sortingEnabled = self.plateList.isSortingEnabled()
        self.plateList.setSortingEnabled(False)
        item = self.plateList.item(0)
        item.setText(_translate("PlateFinder", "No plates detected"))
        self.plateList.setSortingEnabled(__sortingEnabled)
        self.groupBox_4.setTitle(_translate("PlateFinder", "Detected licence plate"))
        self.plateImg.setText(_translate("PlateFinder", "No lic plate yet"))
        self.groupBox_2.setTitle(_translate("PlateFinder", "Controls"))
        self.bWeb.setText(_translate("PlateFinder", "Webcam"))
        self.bClr.setText(_translate("PlateFinder", "Clear"))
        self.bLoad.setText(_translate("PlateFinder", "Load"))

