# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OpenCVThresholder(object):
    def setupUi(self, OpenCVThresholder):
        OpenCVThresholder.setObjectName("OpenCVThresholder")
        OpenCVThresholder.resize(890, 639)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(OpenCVThresholder.sizePolicy().hasHeightForWidth())
        OpenCVThresholder.setSizePolicy(sizePolicy)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(OpenCVThresholder)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Input = QtWidgets.QGroupBox(OpenCVThresholder)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Input.sizePolicy().hasHeightForWidth())
        self.Input.setSizePolicy(sizePolicy)
        self.Input.setMinimumSize(QtCore.QSize(50, 100))
        self.Input.setObjectName("Input")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Input)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.inImage = QtWidgets.QLabel(self.Input)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inImage.sizePolicy().hasHeightForWidth())
        self.inImage.setSizePolicy(sizePolicy)
        self.inImage.setMinimumSize(QtCore.QSize(0, 0))
        self.inImage.setObjectName("inImage")
        self.horizontalLayout_2.addWidget(self.inImage)
        self.horizontalLayout.addWidget(self.Input)
        self.Output = QtWidgets.QGroupBox(OpenCVThresholder)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Output.sizePolicy().hasHeightForWidth())
        self.Output.setSizePolicy(sizePolicy)
        self.Output.setMinimumSize(QtCore.QSize(50, 100))
        self.Output.setObjectName("Output")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.Output)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.outImage = QtWidgets.QLabel(self.Output)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outImage.sizePolicy().hasHeightForWidth())
        self.outImage.setSizePolicy(sizePolicy)
        self.outImage.setMinimumSize(QtCore.QSize(0, 0))
        self.outImage.setObjectName("outImage")
        self.horizontalLayout_3.addWidget(self.outImage)
        self.horizontalLayout.addWidget(self.Output)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(OpenCVThresholder)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.layTop = QtWidgets.QHBoxLayout()
        self.layTop.setObjectName("layTop")
        self.label = QtWidgets.QLabel(OpenCVThresholder)
        self.label.setObjectName("label")
        self.layTop.addWidget(self.label)
        self.horizontalSlider = QtWidgets.QSlider(OpenCVThresholder)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.layTop.addWidget(self.horizontalSlider)
        self.verticalLayout.addLayout(self.layTop)
        self.layBot = QtWidgets.QHBoxLayout()
        self.layBot.setObjectName("layBot")
        self.label_2 = QtWidgets.QLabel(OpenCVThresholder)
        self.label_2.setObjectName("label_2")
        self.layBot.addWidget(self.label_2)
        self.horizontalSlider_2 = QtWidgets.QSlider(OpenCVThresholder)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.layBot.addWidget(self.horizontalSlider_2)
        self.verticalLayout.addLayout(self.layBot)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.line_2 = QtWidgets.QFrame(OpenCVThresholder)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_4 = QtWidgets.QPushButton(OpenCVThresholder)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_4.addWidget(self.pushButton_4)
        self.pushButton_3 = QtWidgets.QPushButton(OpenCVThresholder)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_4.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(OpenCVThresholder)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(OpenCVThresholder)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)

        self.retranslateUi(OpenCVThresholder)
        QtCore.QMetaObject.connectSlotsByName(OpenCVThresholder)

    def retranslateUi(self, OpenCVThresholder):
        _translate = QtCore.QCoreApplication.translate
        OpenCVThresholder.setWindowTitle(_translate("OpenCVThresholder", "EzPlot"))
        self.Input.setTitle(_translate("OpenCVThresholder", "Input Image"))
        self.inImage.setText(_translate("OpenCVThresholder", "No Image Loaded"))
        self.Output.setTitle(_translate("OpenCVThresholder", "Output Image"))
        self.outImage.setText(_translate("OpenCVThresholder", "No Image Loaded"))
        self.label.setText(_translate("OpenCVThresholder", "Lower Threshold"))
        self.label_2.setText(_translate("OpenCVThresholder", "Upper Threshold"))
        self.pushButton_4.setText(_translate("OpenCVThresholder", "Load"))
        self.pushButton_3.setText(_translate("OpenCVThresholder", "Clear"))
        self.pushButton_2.setText(_translate("OpenCVThresholder", "Add"))
        self.pushButton.setText(_translate("OpenCVThresholder", "Save"))


